# Generated by Django 2.2.1 on 2019-10-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_auto_20191007_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='LoginUser',
        ),
    ]
